### ISSUE TITLE
Solution File

### ISSUE THREAD

**Issue by shaheerahmadch** [DixitJoshi12/Ag-Grid-In-PCF#1]
Hello, 
Hope you're doing well. 
I just wanted to add if you could add a solution.zip file to the repository as well as release.
Regards

**Comment by cshiflett** [comment]
Zip file is there, however, it is unusable.  Corrupt file, perhaps.

**Comment by DixitJoshi12** [comment]
Hey Guys I checked the zip it's working perfectly when I clone the repo and import the zip in the power app(Canvas).
path of the zip is "Solutions/bin/Debug/Solutions(zip)".

**Comment by DixitJoshi12** [comment]
However, I will share how to create a zip file on your own. may be in a couple of days Thx.

**Comment by cshiflett** [comment]
The solution will not import.  I will wait for your instructions.  Thanks.
![error](https://github.com/DixitJoshi12/Ag-Grid-In-PCF/assets/60513238/066dadf8-bb2d-48bb-ad5c-e8a03ec5c11e)

**Comment by shaheerahmadch** [comment]
![image](https://github.com/DixitJoshi12/Ag-Grid-In-PCF/assets/114233717/d697732c-5a52-427b-bd40-ff918356d59d)

**Comment by DixitJoshi12** [comment]
see the article https://nebulaaitsolutions.com/blog/web-resource-content-size-is-too-big-in-pcf-control for importing the large size custom control.

**Comment by shaheerahmadch** [comment]
Imported.
