### ISSUE TITLE
Get Selected Item

### ISSUE THREAD

**Issue by shaheerahmadch** [DixitJoshi12/Ag-Grid-In-PCF#4]
Hello, is there a way to get the selected item/s?

**Comment by DixitJoshi12** [comment]
onGridReady={(params: any) => {
                    gridApi = params.api;
                    gridApi.addEventListener('selectionChanged', function() {
                        // Get selected rows when the selection changes
                        console.log(gridApi.getSelectedRows());
                    });
                }}
this will help you to get the selected Rows, However you need to customize your code.

**Comment by DixitJoshi12** [comment]
closing this issue as this is out of scope for this project.
